# Generated by Django 5.1.2 on 2024-10-18 05:07

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/gallery_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('special_about_place', models.CharField(max_length=30)),
                ('featured_image', models.ImageField(upload_to='houses/featured_image/')),
                ('exact_location', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('contact_email', models.EmailField(max_length=254)),
                ('number_of_guests', models.IntegerField(help_text='Maximum number of occupants. Must be greater than 0.', validators=[django.core.validators.MinValueValidator(1, message='Number of guests must be at least 1.')])),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Rent amount in INR. Must be greater than or equal to 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Rent amount cannot be negative.')])),
                ('property_type', models.CharField(help_text='Enter the type of property (e.g., Apartment, Villa, etc.).', max_length=255)),
                ('number_of_bedrooms', models.IntegerField(help_text='Enter the number of bedrooms. Must be greater than or equal to 0.', validators=[django.core.validators.MinValueValidator(0, message='Number of bedrooms cannot be negative.')])),
                ('number_of_bathrooms', models.IntegerField(help_text='Enter the number of bathrooms. Must be greater than or equal to 0.', validators=[django.core.validators.MinValueValidator(0, message='Number of bathrooms cannot be negative.')])),
                ('extra_features', models.TextField(help_text='Any additional features or descriptions')),
                ('lease_duration', models.IntegerField(help_text='Lease duration in days')),
                ('parking_available', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
