# Generated by Django 5.1.2 on 2024-10-17 09:09

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='houses/featured_image/')),
                ('exact_location', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('contact_email', models.EmailField(max_length=254)),
                ('number_of_guests', models.IntegerField(help_text='Maximum number of occupants. Must be greater than 0.', validators=[django.core.validators.MinValueValidator(1, message='Number of guests must be at least 1.')])),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Rent amount in INR. Must be greater than or equal to 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Rent amount cannot be negative.')])),
                ('property_type', models.CharField(help_text='Enter the type of property (e.g., Apartment, Villa, etc.).', max_length=255)),
                ('number_of_bedrooms', models.IntegerField(help_text='Enter the number of bedrooms. Must be greater than or equal to 0.', validators=[django.core.validators.MinValueValidator(0, message='Number of bedrooms cannot be negative.')])),
                ('number_of_bathrooms', models.IntegerField(help_text='Enter the number of bathrooms. Must be greater than or equal to 0.', validators=[django.core.validators.MinValueValidator(0, message='Number of bathrooms cannot be negative.')])),
                ('extra_features', models.TextField(blank=True, help_text='Any additional features or descriptions')),
                ('lease_duration', models.IntegerField(blank=True, help_text='Lease duration in days', null=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/gallery_images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='houses.houselisting')),
            ],
        ),
    ]
