# Generated by Django 5.1.2 on 2024-10-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='location_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.location'),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='houses.houselisting'),
        ),
    ]
