# Generated by Django 5.1.2 on 2024-10-18 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='rent_amount',
            field=models.IntegerField(help_text='Rent amount in INR. Must be greater than or equal to 0.', validators=[django.core.validators.MinValueValidator(0, message='Rent amount cannot be negative.')]),
        ),
    ]
