import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/Authcontext";
import Navbar from "@/Components/general/navbar/Navbar";
import { LocationProvider } from "@/context/Locationcontext";
import Footer from "@/Components/general/footer/Footer";
import { HouseProvider } from "@/context/HouseContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AuthProvider>
					<LocationProvider>
						<HouseProvider>
							<ToastContainer />
							<Navbar />
							<div className="pt-[65px]">{children}</div>
							<Footer />
						</HouseProvider>
					</LocationProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
