# Generated by Django 5.1.2 on 2024-11-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_connection_customer_alter_connection_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
    ]
